; ================================================================================
; Sprite Mappings - generated by Flex 2 Sat Feb 06 2021 20:18:45 GMT-0500 (Eastern Standard Time)
; ================================================================================

DATAEJIE48A4BMI:
	dc.w DATAEJIE48A4BMI_0-DATAEJIE48A4BMI, DATAEJIE48A4BMI_1-DATAEJIE48A4BMI
	dc.w DATAEJIE48A4BMI_2-DATAEJIE48A4BMI, DATAEJIE48A4BMI_3-DATAEJIE48A4BMI
	dc.w DATAEJIE48A4BMI_4-DATAEJIE48A4BMI, DATAEJIE48A4BMI_5-DATAEJIE48A4BMI
	dc.w DATAEJIE48A4BMI_6-DATAEJIE48A4BMI, DATAEJIE48A4BMI_7-DATAEJIE48A4BMI
DATAEJIE48A4BMI_0: dc.b $B
	dc.b $F8, $5, $0, $88, $C4
	dc.b $F8, $5, $0, $B2, $D4
	dc.b $F8, $5, $0, $AE, $E4
	dc.b $F8, $5, $0, $C2, $F4
	dc.b $F8, $1, $0, $A0, $4
	dc.b $F8, $5, $0, $AE, $C
	dc.b $F8, $5, $0, $C6, $1C
	dc.b $F8, $5, $0, $90, $2C
	dc.b $38, $5, $20, $21, $E8
	dc.b $38, $5, $20, $21, $8
	dc.b $36, $5, $1, $FC, $F8
DATAEJIE48A4BMI_1: dc.b $3
	dc.b $4, $5, $0, $15, $FB
	dc.b $F4, $A, $0, $6, $EC
	dc.b $F4, $6, $0, $F, $4
DATAEJIE48A4BMI_2: dc.b $3
	dc.b $4, $5, $0, $19, $FB
	dc.b $F4, $A, $0, $6, $EC
	dc.b $F4, $6, $0, $F, $4
DATAEJIE48A4BMI_3: dc.b $3
	dc.b $4, $5, $0, $1D, $FB
	dc.b $F4, $A, $0, $6, $EC
	dc.b $F4, $6, $0, $F, $4
DATAEJIE48A4BMI_4: dc.b $2
	dc.b $60, $9, $20, $0, $E8
	dc.b $60, $9, $28, $0, $0
DATAEJIE48A4BMI_5: dc.b $1
	dc.b $0, $6, $0, $12, $0
DATAEJIE48A4BMI_6: dc.b $1
	dc.b $0, $6, $0, $12, $0
DATAEJIE48A4BMI_7: dc.b $1
	dc.b $0, $6, $0, $18, $0
	even