; ================================================================================
; Sprite Mappings - generated by Flex 2 Sat Feb 06 2021 21:05:36 GMT-0500 (Eastern Standard Time)
; ================================================================================

DATA5432R1WHLX8:
	dc.w DATA5432R1WHLX8_0-DATA5432R1WHLX8, DATA5432R1WHLX8_1-DATA5432R1WHLX8
	dc.w DATA5432R1WHLX8_2-DATA5432R1WHLX8, DATA5432R1WHLX8_3-DATA5432R1WHLX8
	dc.w DATA5432R1WHLX8_4-DATA5432R1WHLX8, DATA5432R1WHLX8_5-DATA5432R1WHLX8
	dc.w DATA5432R1WHLX8_6-DATA5432R1WHLX8, DATA5432R1WHLX8_7-DATA5432R1WHLX8
DATA5432R1WHLX8_0: dc.b $B
	dc.b $F8, $5, $0, $88, $C4
	dc.b $F8, $5, $0, $B2, $D4
	dc.b $F8, $5, $0, $AE, $E4
	dc.b $F8, $5, $0, $C2, $F4
	dc.b $F8, $1, $0, $A0, $4
	dc.b $F8, $5, $0, $AE, $C
	dc.b $F8, $5, $0, $C6, $1C
	dc.b $F8, $5, $0, $90, $2C
	dc.b $38, $5, $20, $6, $E8
	dc.b $38, $5, $20, $6, $8
	dc.b $36, $5, $1, $FC, $F8
DATA5432R1WHLX8_1: dc.b $2
	dc.b $F4, $E, $0, $A, $F4
	dc.b $FC, $1, $0, $16, $EC
DATA5432R1WHLX8_2: dc.b $2
	dc.b $F4, $E, $0, $18, $F4
	dc.b $FC, $1, $0, $16, $EC
DATA5432R1WHLX8_3: dc.b $2
	dc.b $F4, $E, $0, $18, $F4
	dc.b $FC, $1, $0, $16, $EC
DATA5432R1WHLX8_4: dc.b $2
	dc.b $60, $9, $20, $0, $E8
	dc.b $60, $9, $28, $0, $0
DATA5432R1WHLX8_5: dc.b $1
	dc.b $0, $6, $0, $12, $0
DATA5432R1WHLX8_6: dc.b $1
	dc.b $0, $6, $0, $12, $0
DATA5432R1WHLX8_7: dc.b $1
	dc.b $0, $6, $0, $18, $0
	even