; ================================================================================
; Sprite Mappings - generated by Flex 2 Sat Feb 06 2021 20:34:31 GMT-0500 (Eastern Standard Time)
; ================================================================================

DATA7CZB0DBXAPK:
	dc.w DATA7CZB0DBXAPK_0-DATA7CZB0DBXAPK, DATA7CZB0DBXAPK_1-DATA7CZB0DBXAPK
	dc.w DATA7CZB0DBXAPK_2-DATA7CZB0DBXAPK, DATA7CZB0DBXAPK_3-DATA7CZB0DBXAPK
	dc.w DATA7CZB0DBXAPK_4-DATA7CZB0DBXAPK, DATA7CZB0DBXAPK_5-DATA7CZB0DBXAPK
	dc.w DATA7CZB0DBXAPK_6-DATA7CZB0DBXAPK, DATA7CZB0DBXAPK_7-DATA7CZB0DBXAPK
DATA7CZB0DBXAPK_0: dc.b $B
	dc.b $F8, $5, $0, $88, $C4
	dc.b $F8, $5, $0, $B2, $D4
	dc.b $F8, $5, $0, $AE, $E4
	dc.b $F8, $5, $0, $C2, $F4
	dc.b $F8, $1, $0, $A0, $4
	dc.b $F8, $5, $0, $AE, $C
	dc.b $F8, $5, $0, $C6, $1C
	dc.b $F8, $5, $0, $90, $2C
	dc.b $38, $5, $20, $6, $E8
	dc.b $38, $5, $20, $6, $8
	dc.b $36, $5, $1, $FC, $F8
DATA7CZB0DBXAPK_1: dc.b $2
	dc.b $F4, $A, $0, $A, $FC
	dc.b $FC, $5, $0, $13, $EC
DATA7CZB0DBXAPK_2: dc.b $2
	dc.b $F4, $A, $0, $17, $FC
	dc.b $FC, $5, $0, $13, $EC
DATA7CZB0DBXAPK_3: dc.b $2
	dc.b $F8, $A, $0, $20, $FC
	dc.b $FC, $5, $0, $13, $EC
DATA7CZB0DBXAPK_4: dc.b $2
	dc.b $60, $9, $20, $0, $E8
	dc.b $60, $9, $28, $0, $0
DATA7CZB0DBXAPK_5: dc.b $1
	dc.b $0, $6, $0, $12, $0
DATA7CZB0DBXAPK_6: dc.b $1
	dc.b $0, $6, $0, $12, $0
DATA7CZB0DBXAPK_7: dc.b $1
	dc.b $0, $6, $0, $18, $0
	even