; ================================================================================
; Sprite Mappings - generated by Flex 2 Wed Jan 27 2021 12:05:17 GMT-0500 (Eastern Standard Time)
; ================================================================================

DATA9EPX4WOJQ9:
	dc.w DATA9EPX4WOJQ9_0-DATA9EPX4WOJQ9, DATA9EPX4WOJQ9_1-DATA9EPX4WOJQ9
	dc.w DATA9EPX4WOJQ9_2-DATA9EPX4WOJQ9, DATA9EPX4WOJQ9_3-DATA9EPX4WOJQ9
	dc.w DATA9EPX4WOJQ9_4-DATA9EPX4WOJQ9, DATA9EPX4WOJQ9_5-DATA9EPX4WOJQ9
	dc.w DATA9EPX4WOJQ9_6-DATA9EPX4WOJQ9, DATA9EPX4WOJQ9_7-DATA9EPX4WOJQ9
DATA9EPX4WOJQ9_0: dc.b $2
	dc.b $EC, $B, $0, $0, $F8
	dc.b $C, $C, $0, $C, $F0
DATA9EPX4WOJQ9_1: dc.b $3
	dc.b $FC, $D, $0, $10, $F0
	dc.b $EC, $B, $0, $0, $F8
	dc.b $C, $C, $0, $C, $F0
DATA9EPX4WOJQ9_2: dc.b $2
	dc.b $EC, $9, $0, $18, $F8
	dc.b $FC, $E, $0, $1E, $F0
DATA9EPX4WOJQ9_3: dc.b $2
	dc.b $EC, $9, $0, $2A, $F8
	dc.b $FC, $E, $0, $30, $F0
DATA9EPX4WOJQ9_4: dc.b $2
	dc.b $EC, $9, $8, $2A, $F0
	dc.b $FC, $E, $8, $30, $F0
DATA9EPX4WOJQ9_5: dc.b $4
	dc.b $F4, $9, $0, $3C, $F4
	dc.b $C, $8, $0, $42, $F4
	dc.b $EC, $0, $0, $45, $FC
	dc.b $4, $C, $0, $46, $F0
DATA9EPX4WOJQ9_6: dc.b $7
	dc.b $B2, $C, $0, $4A, $F8
	dc.b $BA, $F, $0, $4E, $F0
	dc.b $BA, $5, $0, $5E, $10
	dc.b $CA, $2, $0, $62, $10
	dc.b $DA, $C, $0, $65, $F0
	dc.b $E2, $8, $0, $69, $F8
	dc.b $EA, $5, $0, $6C, $F8
DATA9EPX4WOJQ9_7: dc.b $18
	dc.b $80, $F, $0, $70, $F8
	dc.b $90, $B, $0, $80, $E0
	dc.b $90, $B, $0, $8C, $18
	dc.b $98, $B, $0, $98, $30
	dc.b $A0, $F, $0, $A4, $58
	dc.b $88, $0, $0, $B4, $F0
	dc.b $80, $5, $0, $B5, $18
	dc.b $A0, $F, $0, $B9, $F8
	dc.b $B0, $B, $0, $C9, $E0
	dc.b $B8, $F, $0, $D5, $38
	dc.b $A8, $5, $0, $E5, $48
	dc.b $C0, $2, $0, $E9, $58
	dc.b $C0, $F, $0, $EC, $F8
	dc.b $B8, $F, $0, $FC, $18
	dc.b $B0, $8, $1, $C, $18
	dc.b $D8, $D, $1, $F, $30
	dc.b $D8, $8, $1, $17, $18
	dc.b $D8, $F, $1, $1A, $D8
	dc.b $E0, $D, $1, $2A, $F8
	dc.b $E0, $0, $1, $32, $28
	dc.b $D0, $4, $1, $33, $E0
	dc.b $E8, $5, $1, $35, $C8
	dc.b $F8, $C, $1, $39, $C8
	dc.b $F0, $6, $1, $3D, $F8
	even