; ================================================================================
; Sprite Mappings - generated by Flex 2 Wed Jan 27 2021 15:48:18 GMT-0500 (Eastern Standard Time)
; ================================================================================

DATA9G2Q6Z2SEME:
	dc.w DATA9G2Q6Z2SEME_0-DATA9G2Q6Z2SEME, DATA9G2Q6Z2SEME_1-DATA9G2Q6Z2SEME
	dc.w DATA9G2Q6Z2SEME_2-DATA9G2Q6Z2SEME, DATA9G2Q6Z2SEME_3-DATA9G2Q6Z2SEME
	dc.w DATA9G2Q6Z2SEME_4-DATA9G2Q6Z2SEME, DATA9G2Q6Z2SEME_5-DATA9G2Q6Z2SEME
	dc.w DATA9G2Q6Z2SEME_6-DATA9G2Q6Z2SEME, DATA9G2Q6Z2SEME_7-DATA9G2Q6Z2SEME
DATA9G2Q6Z2SEME_0: dc.b $3
	dc.b $EC, $B, $0, $0, $F4
	dc.b $C, $8, $0, $C, $F4
	dc.b $FD, $0, $0, $F, $C
DATA9G2Q6Z2SEME_1: dc.b $4
	dc.b $FB, $D, $0, $10, $F0
	dc.b $EC, $B, $0, $0, $F4
	dc.b $C, $8, $0, $C, $F4
	dc.b $FD, $0, $0, $F, $C
DATA9G2Q6Z2SEME_2: dc.b $4
	dc.b $EC, $B, $0, $18, $FB
	dc.b $F4, $5, $0, $24, $EB
	dc.b $F4, $2, $0, $28, $13
	dc.b $C, $8, $0, $2B, $F3
DATA9G2Q6Z2SEME_3: dc.b $4
	dc.b $F4, $E, $8, $2E, $F5
	dc.b $EC, $8, $8, $3A, $F5
	dc.b $C, $8, $8, $3D, $F5
	dc.b $FC, $1, $8, $40, $ED
DATA9G2Q6Z2SEME_4: dc.b $4
	dc.b $F4, $E, $0, $2E, $EB
	dc.b $EC, $8, $0, $3A, $F3
	dc.b $C, $8, $0, $3D, $F3
	dc.b $FC, $1, $0, $40, $B
DATA9G2Q6Z2SEME_5: dc.b $3
	dc.b $ED, $B, $0, $42, $F0
	dc.b $D, $C, $0, $4E, $F0
	dc.b $FD, $0, $0, $52, $8
DATA9G2Q6Z2SEME_6: dc.b $2
	dc.b $CA, $F, $0, $53, $EB
	dc.b $EA, $4, $0, $63, $FB
DATA9G2Q6Z2SEME_7: dc.b $F
	dc.b $84, $F, $0, $65, $0
	dc.b $84, $3, $0, $75, $20
	dc.b $8C, $3, $0, $79, $F8
	dc.b $94, $3, $0, $7D, $F0
	dc.b $9C, $3, $0, $81, $E8
	dc.b $A4, $B, $0, $85, $0
	dc.b $A4, $4, $0, $91, $18
	dc.b $AC, $3, $0, $93, $F8
	dc.b $AC, $0, $0, $97, $18
	dc.b $B4, $3, $0, $98, $F0
	dc.b $BC, $0, $0, $9C, $E8
	dc.b $C4, $A, $0, $9D, $0
	dc.b $CC, $3, $0, $A6, $F8
	dc.b $CC, $1, $0, $AA, $18
	dc.b $DC, $1, $0, $AC, $0
	even